export const environment = {
  production: true,
  stripe_token: 'STRIPE_TOKEN',
  paypal_token: 'PAYPAL_TOKEN',
  baseUrl: '',
  devTenancyName: '',
  tenantId: null as number | null,
  storeId: null as string | null,
  googleMapsApiKey: 'AIzaSyDyeIndELQj_horM-429SavXuMHojQ62P0',
  googleClientId: '463817211807-kd2tc0n3us50bc4qt5srp9jvr7qoa4oi.apps.googleusercontent.com',
  urls: {
    Account_IsTenantAvailable: 'Account/IsTenantAvailable',
    OnlineShopAvailableProduct_GetAllAvailableProductsForOnlineShop:
      'OnlineShopAvailableProduct/GetAllAvailableProductsForOnlineShop',
    OnlineShopAvailableProduct_GetProductDetailForOnlineShop:
      'OnlineShopAvailableProduct/GetProductDetailForOnlineShop',
    OnlineShopAvailableProduct_GetRelatedProductsForOnlineShop:
      'OnlineShopAvailableProduct/GetRelatedProductsForOnlineShop',
    OnlineShopBrand_GetBrandsListForOnline: 'OnlineShopBrand/GetBrandsListForOnline',
    OnlineShopBrand_GetHomePopularBrandsForOnline: 'OnlineShopBrand/GetHomePopularBrandsForOnline',
    OnlineShopAvailableProduct_GetProductColorsListForOnline:
      'OnlineShopAvailableProduct/GetProductColorsListForOnline',
    OnlineShopAvailableProduct_GetProductSizesListForOnline:
      'OnlineShopAvailableProduct/GetProductSizesListForOnline',
    OnlineShopWishlist_GetWishlistForOnlineShop: 'OnlineShopWishlist/GetWishlistForOnlineShop',
    OnlineShopWishlist_AddToWishlistForOnlineShop: 'OnlineShopWishlist/AddToWishlistForOnlineShop',
    OnlineShopWishlist_RemoveFromWishlistForOnlineShop:
      'OnlineShopWishlist/RemoveFromWishlistForOnlineShop',
    OnlineShopCheckout_GetShippingRate: 'OnlineShopCheckout/GetShippingRate',
    OnlineShopCheckout_ApplyCoupon: 'OnlineShopCheckout/ApplyCoupon',
    OnlineShopSaleOrder_CreateOnlineShopSaleOrder: 'OnlineShopSaleOrder/CreateOnlineShopSaleOrder',
    OnlineShopSaleOrder_GetForSuccessPage: 'OnlineShopSaleOrder/GetOnlineShopSaleOrderForSuccessPage',
    OnlineShopSaleOrder_GetMyOrders: 'OnlineShopSaleOrder/GetMyOnlineShopSaleOrdersForCustomer',
    OnlineShopSaleOrder_GetMyOrderDetail: 'OnlineShopSaleOrder/GetMyOnlineShopSaleOrderDetailForCustomer',
    OnlineShopSaleOrder_GetMyOrderStatusTimeline: 'OnlineShopSaleOrder/GetMyOnlineShopOrderStatusTimelineForCustomer',
    OnlineShopSaleOrder_GetOrderReceipt: 'OnlineShopSaleOrder/GetMyOrderReceiptHtml',
    OnlineShopSaleOrder_DownloadOrderReceiptPdf: 'OnlineShopSaleOrder/DownloadMyOrderReceiptPdf',
    OnlineShopSaleOrder_PreviewOrderReceiptPdf: 'OnlineShopSaleOrder/PreviewMyOrderReceiptPdf',
    OnlineShopShipment_TrackOrder: 'OnlineShopShipment/TrackOrder',
    OnlineShopShipment_SyncOrderTracking: 'OnlineShopShipment/SyncOrderTracking',
    OnlineShopShipment_ResyncOrderTracking: 'OnlineShopShipment/ResyncOrderTracking',
    OnlinseShopUsers_SignupForOnlineShop: 'OnlinseShopUsers/SignupForOnlineShop',
    OnlinseShopUsers_ResetPasswordRequestForOnlineShop:
      'OnlinseShopUsers/ResetPasswordRequestForOnlineShop',
    OnlinseShopUsers_GetCustomerProfileForOnlineShop:
      'OnlinseShopUsers/GetCustomerProfileForOnlineShop',
    Page_GetBySlug: 'OnlineShopPage/GetBySlug',
    Page_GetActivePages: 'OnlineShopPage/GetActivePages',
    Settings_GetForStorefront: 'OnlineShopSettings/GetForStorefront',
    HeaderMenu_GetForStorefront: 'OnlineShopHeaderMenu/GetForStorefront',
    OnlineShopHomeBanner_GetForStorefront: 'OnlineShopHomeBanner/GetHomeBannersForStorefront',
    Notification_GetAll: 'Notification/GetNotifications',
    Notification_GetUnread: 'Notification/GetUnreadCustomerNotifications',
    Notification_Update: 'Notification/UpdateNotification',
    Notification_MarkAsRead: 'Notification/MarkCustomerNotificationAsRead',
    OnlineShopProductGroup_GetHierarchyForOnline: 'OnlineShopProductGroup/GetProductGroupHierarchyForOnline',
    OnlineShopProductGroup_GetProductGroupsListForOnline: 'OnlineShopProductGroup/GetProductGroupsListForOnline',
    OnlineShopSearch_GetSuggestions: 'OnlineShopSearch/GetSearchSuggestions',
    OnlineShopTenant_GetTenantDetailsForWebsite: 'OnlineShopTenant/GetTenantDetailsForWebsite',
  },
  shop: {
    tenantId: '1',
    storeId: null as string | null,
    tenancyName: '',
  },
  auth: {
    login: 'TokenAuth/AuthenticateForOnlineShop',
    signup: 'User/SignupForMobile',
    resetPassword: 'User/ResetPasswordRequestForMobile',
  },
};
