// Capacitor Android APK pointed at the PROD API (no local dev tunnel).

export const environment = {
  production: true,
  isMobileApp: true,
  stripe_token: 'STRIPE_TOKEN',
  paypal_token: 'PAYPAL_TOKEN',
  baseUrl: 'https://prod-onlineshopping-api.sastakhareedo.com/',
  /** Sent to WebsiteTenantResolver (APK WebView is not the real storefront host). */
  devHostName: 'sastakhareedo.com',
  devTenancyName: 'beta-ak-mobile-shop',
  devTenantId: 1,
  tenantId: null as number | null,
  storeId: null as string | null,
  googleMapsApiKey: 'AIzaSyDyeIndELQj_horM-429SavXuMHojQ62P0',
  googleClientId: '463817211807-kd2tc0n3us50bc4qt5srp9jvr7qoa4oi.apps.googleusercontent.com',
  urls: {
    Account_IsTenantAvailable: 'Account/IsTenantAvailable',
    WebsiteTenantResolver_ResolveTenantByDomain: 'WebsiteTenantResolver/ResolveTenantByDomain',
    Notification_GetAll: 'Notification/GetNotifications',
    Notification_GetUnread: 'Notification/GetUnreadCustomerNotifications',
    Notification_Update: 'Notification/UpdateNotification',
    Notification_MarkAsRead: 'Notification/MarkCustomerNotificationAsRead',
    Notification_MarkAllAsRead: 'Notification/MarkAllCustomerNotificationsAsRead',
    OnlineShopAvailableProduct_GetAllAvailableProductsForOnlineShop: 'OnlineShopAvailableProduct/GetAllAvailableProductsForOnlineShop',
    OnlineShopAvailableProduct_GetProductDetailForOnlineShop: 'OnlineShopAvailableProduct/GetProductDetailForOnlineShop',
    OnlineShopAvailableProduct_GetRelatedProductsForOnlineShop: 'OnlineShopAvailableProduct/GetRelatedProductsForOnlineShop',
    OnlineShopBrand_GetBrandsListForOnline: 'OnlineShopBrand/GetBrandsListForOnline',
    OnlineShopBrand_GetHomePopularBrandsForOnline: 'OnlineShopBrand/GetHomePopularBrandsForOnline',
    OnlineShopAvailableProduct_GetProductColorsListForOnline: 'OnlineShopAvailableProduct/GetProductColorsListForOnlineShop',
    OnlineShopAvailableProduct_GetProductSizesListForOnline: 'OnlineShopAvailableProduct/GetProductSizesListForOnlineShop',
    OnlineShopAvailableProduct_GetProductBrandsListForOnline: 'OnlineShopAvailableProduct/GetProductBrandsListForOnlineShop',
    OnlineShopAvailableProduct_GetHomePopularCategoryProductSliders: 'OnlineShopAvailableProduct/GetHomePopularCategoryProductSliders',
    OnlineShopProduct_GetHomePopularCategoryProductSliders: 'OnlineShopProduct/GetHomePopularCategoryProductSliders',
    OnlineShopWishlist_GetWishlistForOnlineShop: 'OnlineShopWishlist/GetWishlistForOnlineShop',
    OnlineShopWishlist_AddToWishlistForOnlineShop: 'OnlineShopWishlist/AddToWishlistForOnlineShop',
    OnlineShopWishlist_RemoveFromWishlistForOnlineShop: 'OnlineShopWishlist/RemoveFromWishlistForOnlineShop',
    OnlineShopCheckout_CalculatePricing: 'OnlineShopCheckout/CalculatePricing',
    WorkingArea_IsPointInside: 'OnlineShopStoreWorkingLocation/IsPointInsideWorkingArea',
    OnlineShopSaleOrder_CreateOnlineShopSaleOrder: 'OnlineShopSaleOrder/CreateOnlineShopSaleOrder',
    OnlineShopSaleOrder_GetForSuccessPage: 'OnlineShopSaleOrder/GetOnlineShopSaleOrderForSuccessPage',
    OnlineShopSaleOrder_GetForFailurePage: 'OnlineShopSaleOrder/GetOnlineShopSaleOrderForPaymentFailurePage',
    OnlineShopSaleOrder_GetMyOrders: 'OnlineShopSaleOrder/GetMyOnlineShopSaleOrdersForCustomer',
    OnlineShopSaleOrder_HideMyOrder: 'OnlineShopSaleOrder/HideMyOnlineShopSaleOrderForCustomer',
    OnlineShopSaleOrder_GetMyOrderDetail: 'OnlineShopSaleOrder/GetMyOnlineShopSaleOrderDetailForCustomer',
    OnlineShopSaleOrder_GetMyOrderStatusTimeline: 'OnlineShopSaleOrder/GetMyOnlineShopOrderStatusTimelineForCustomer',
    OnlineShopSaleOrder_GetOrderReceipt: 'OnlineShopSaleOrder/GetMyOrderReceiptHtml',
    OnlineShopSaleOrder_DownloadOrderReceiptPdf: 'OnlineShopSaleOrder/DownloadMyOrderReceiptPdf',
    OnlineShopSaleOrder_PreviewOrderReceiptPdf: 'OnlineShopSaleOrder/PreviewMyOrderReceiptPdf',
    OnlineShopShipment_TrackOrder: 'OnlineShopShipment/TrackOrder',
    OnlineShopShipment_SyncOrderTracking: 'OnlineShopShipment/SyncOrderTracking',
    OnlineShopShipment_ResyncOrderTracking: 'OnlineShopShipment/ResyncOrderTracking',
    TcsCourier_CreateBookingFromOrder: 'TcsCourier/CreateBookingFromOrder',
    OnlinseShopUsers_SignupForOnlineShop: 'OnlinseShopUsers/SignupForOnlineShop',
    OnlinseShopUsers_ResetPasswordRequestForOnlineShop: 'OnlinseShopUsers/ResetPasswordRequestForOnlineShop',
    OnlinseShopUsers_GetCustomerProfileForOnlineShop: 'OnlinseShopUsers/GetCustomerProfileForOnlineShop',
    Page_GetBySlug: 'OnlineShopPage/GetBySlug',
    Page_GetActivePages: 'OnlineShopPage/GetActivePages',
    Settings_GetForStorefront: 'OnlineShopSettings/GetForStorefront',
    HeaderMenu_GetForStorefront: 'OnlineShopHeaderMenu/GetForStorefront',
    OnlineShopHomeBanner_GetForStorefront: 'OnlineShopHomeBanner/GetHomeBannersForStorefront',
    OnlineShopCoupon_GetActiveFreeShippingPromo: 'OnlineShopCoupon/GetActiveFreeShippingPromoForStorefront',
    OnlineShopShipping_GetShippingDeals: 'OnlineShopShipping/GetShippingDealsForStorefront',
    OnlineShopStoreLogo_GetForStorefront: 'OnlineShopStoreLogo/GetLogoForStorefront',
    OnlineShopProductGroup_GetHierarchyForOnline: 'OnlineShopProductGroup/GetProductGroupHierarchyForOnline',
    OnlineShopProductGroup_GetProductGroupsListForOnline: 'OnlineShopProductGroup/GetProductGroupsListForOnline',
    OnlineShopSearch_GetSuggestions: 'OnlineShopSearch/GetSearchSuggestions',
    OnlineShopTenant_GetTenantDetailsForWebsite: 'OnlineShopTenant/GetTenantDetailsForWebsite',
  },
  shop: {
    tenantId: '1',
    storeId: null as string | null,
    tenancyName: 'beta-ak-mobile-shop',
  },
  auth: {
    login: 'TokenAuth/AuthenticateForOnlineShop',
    signup: 'User/SignupForMobile',
    resetPassword: 'User/ResetPasswordRequestForMobile',
  },
};
